export const quotes = [
  'The right time is always now',
  'Think like a proton: always positive',
  'Do what you can with what you have where you are',
  'Be a light in this world',
  'Life is more than one big to do list',
  'Done is better than perfect',
  'You are stronger than you think',
  'There is no failure: you either win or learn',
  'Growing takes time',
  'Try to be a rainbow in someone’s cloud',
  'Life has no limitations, except the ones you make',
  'The future belongs to those who believe in the beauty of their dreams',
  'If opportunity doesn’t knock, build a door',
  'Walk slowly but never walk backward',
  'Keep calm and keep learning',
  'A little progress each day adds up to big results',
  'Positive thinking must be followed by positive doing',
  'Delete the negative. Accentuate the positive',
  'Prepare to win the night before',
  'Life is not about finding yourself. Life is about creating yourself',
  'All progress takes place outside the comfort zone',
  'The only place where success comes before work is in the dictionary',
  'Your limitation it is only your imagination',
  'Push yourself, because no one else is going to do it for you',
  'Sometimes later becomes never. Do it now',
  'Little things make big days',
  'Create a life you can&apos;t wait to wake up to',
  'You can',
  'Be a warrior, not a worrier',
  'If your dream don&apos;t scare you the aren&apos;t big enough',
  'All we have is now',
  'Keep moving',
  'Enjoy today',
  'Just say yikes and move on',
  'Don’t be a rock when you really are a gem',
  'Better an oops than a what if',
  'Your only limit is you',
  'There is no change where is no action',
  'Enjoy the space between where you are and where you are going',
  'If not now, when?',
  'Worry less and do your best',
  'Life is way too short to spend another day at war with yourself',
  'You are where you are supposed to be',
  'Allow yourself to grow',
  'Prioritize your peace',
  '30% is better than 0%. Give yourself more credit for trying',
  'Decide what kind of life you really want and then say no to everything that is not that',
  'Discovering what you don&apos;t want is just as important as finding out what you do',
  'Nothing changes if nothing changes',
  'Everything is a choice',
  'Life is more than one big to do list',
  'Flowers need time to bloom',
  'Every day is a good day',
  'Your direction is more important than your speed',
  'Old ways won&apos;t open new doors',
  'Try to be a rainbow in someone&apos;s cloud',
  'Do good and good will come to you',
  'Take the first step',
  'One day or day one. It&apos;s your choice',
  'Life is too short to be grumpy',
  'When things aren&apos;t going right, go left',
  'Learn from your mistakes',
];
